spring:
  application:
    name: ts-user-service
  datasource:
    url: "jdbc:postgresql://${DB_URL}/${spring.application.name}"
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${HTTP_PORT}
